# Generated by Django 4.1.7 on 2023-04-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Task', max_length=63),
        ),
    ]
